### ISSUE TITLE
More helpful error message for low transfers

### ISSUE THREAD

**Issue by mvandeberg** [koinos/koinos-cli-wallet#29]
tKOIN has a precision of 8. If I attempt to transfer less than 1 sat of tKOIN, the wallet correctly fails. However, the error message is less than helpful. Perhaps this case should be detected and a message informing the user of the precision of tKOIN should be added.

![Screen Shot 2021-08-11 at 10 37 19](https://user-images.githubusercontent.com/15834128/129077684-a30ed20e-e4aa-498c-bc37-6ad38eeb8384.png)

**Comment by MercurySolar** [comment]
Very detailed report! When I read issues like this, hands itch to fix it. )

**Comment by MercurySolar** [comment]
So you think this error message will be good enough?

invalid amount: cannot transfer 0.000000001 tKOIN, amount should be grater than minimal 0.00000001 (1e-8) tKOIN

**Comment by youkaicountry** [comment]
Resolved
