### ISSUE TITLE
Insufficient transfers appear to work

### ISSUE THREAD

**Issue by mvandeberg** [koinos/koinos-cli-wallet#30]
When transferring more tKOIN than I have, the transfer appears to work. This is perhaps the beginning of a larger discussion on how the token standard should operate (it currently returns true/false depending on success, but the transaction is always a success). However, the wallet should for sure check the balance of an address and prevent transferring more tKOIN than owned and displaying a helpful error message to the user.

![Screen Shot 2021-08-11 at 10 44 20](https://user-images.githubusercontent.com/15834128/129079081-29a46452-5a31-4a42-b801-0fbe52789bab.png)

**Comment by MercurySolar** [comment]
Also noticed this, working on it. Should be ready in hour or so

**Comment by youkaicountry** [comment]
Resolved
